# Server settings
server:
  applicationConnectors:
    - type: http
      port: 8080
  adminConnectors:
    - type: http
      port: 8081

# Database settings using dataSourceFactory
dataSourceFactory:
  driverClass: com.mysql.cj.jdbc.Driver
  user: your_database_user
  password: your_database_password
  url: jdbc:mysql://localhost:3306/your_database_name?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
  properties:
    charSet: UTF-8
    healthCheckValidationQuery: "SELECT 1"
# Logging settings
logging:
  level: INFO
  loggers:
    com.example.todoapp: DEBUG
